Feature : Oauth, User도메인 관련 기능 구현
SSA-FE/formssafe-be pull request #8
Opened 2024-03-19 16:17 UTC by gurwls0122

PR Desciption
-------------
- Google API요청 시 쿼리 스트링을 MultiValueMap으로 넣어줬을 시 생기는 오류 해결
- 회원 정보 조회, 닉네임 변경 기능, oauth로그인 시 사용자 생성(랜덤 nickname) 기능 구현
- User삭제(Oauth 액세스 권한 삭제 및 DB삭제) 구현
- User삭제 flow : (session과 입력 id확인 -> id가 db에 존재하는지 확인 -> 해당 id를 가진 Member의 refreshtoken가져옴 -> refreshtoken기반으로 accesstoken 생성 -> accesstoken으로 구글 계정 연동 끊기 -> db내 데이터 삭제)
- queryDsl 설정 및 test완료. 단, User와 Auth api에서는 너무 간단한 쿼리만 처리하고 기존에 사용하던 jpa에서 바꿀게 없어서 세팅만 해둠.

Requirements for Reviewer
-------------------------
- GoogleRefreshToken, GoogleAccessToken dto가 구조가 거의 비슷한데 
`@JsonNaming(SnakeCaseStrategy.class)` 해당 태그를 하나의 클래스에서 각각의 record로 주입이 안되는 것같아서 빼놓긴 했습니다.. 방법을 아실런지요?

- service내에 선언한 함수명들, oauth 진행과정에서 새롭게 추가된 함수명들 괜찮은지 확인부탁!

PR Log
------
### 발생했던 문제 혹은 어려웠던 점
- MultiValueMap 전 안되서 변경했는데 다른 컴퓨터에서도 되는지 확인 필요
- refreshToken이 초기에만 값이 들어오고 이후엔 null이 들어옴.
- 사용자의 어플리케이션 연동을 끊기 위해 필요한 accessToken을 어떻게 가져올건지 고민 -> Member 테이블에 refresh_token추가해서 access token가져옴

### 새롭게 배우거나 느낀 점
*  querydsl이 생각보다 훨씬 편한 것 같다. 
* 사소한 부분에서 실수가 너무 많아 생각보다 시간을 너무 많이 썻다. 그래도 설계를 잘해놓은 덕에 쉽게 해결했다

### 고민 사항
- 현재 refreshToken이 초기에 한번만 발급되는 구조를 가지고 있어, 모든 로그인 요청에 대해 초기 요청과 같은 수락 처리를 진행하고 있음 -> 아마 세션이 저장되어있어도 해당 구조가 반복될 것 같아 로그인 로직을 바꾸거나, refreshToken을 member에 저장할때 `Transactional`하게 저장할 수 있는 방법을 찾아보고 싶음.
- 에러 코드 처리 어떻게 할 것인지 확인.

2024-03-20 00:44 UTC, minnim1010 commented
1. 두 dto에서 필요한 모든 속성을 정의하면 request 매핑 시 없는 값을 null로 받아와진다고 생각이 드는데, 해보셨을까요?

고생하셨습니다!!!

2024-03-20 00:49 UTC, minnim1010 commented
1. MultiValueMap 관련 문제: 가끔 class 패스 삐끗해서 에러 날 때도 있거든요. 혹시 gradle clean 후 build 다시 해보심이?
2.

2024-03-20 00:50 UTC, minnim1010 reviewed
고생 많으셨습니다~~!

2024-03-20 00:50 UTC, minnim1010 commented on src/main/java/com/formssafe/domain/user/entity/User.java
> +@Setter
❗️엔티티에 setter를 사용하면 실수로 db에 있는 데이터가 변경될 수 있는 여지가 생기므로, setter 사용이 아닌 컬럼을 변경하는 메서드를 직접 사용하면 좋을 것 같습니다.

2024-03-20 00:50 UTC, minnim1010 commented on src/main/java/com/formssafe/domain/user/entity/User.java
>  @AllArgsConstructor
❗️Builder를 사용하므로 AllArgsConstructor를 사용할 일이 없을 거라 생각하고, builder나 생성자 둘 중 하나만 사용하는 것이 코드 일관성, 일관적인 유효성 검사를 위해 좋아보여서 삭제하는 것이 어떨까요?

2024-03-20 00:50 UTC, minnim1010 commented on src/main/java/com/formssafe/domain/oauth/service/OAuthService.java
> +    public String generateRandomNickname(){
❗️이 로직은 현재는 OauthService에서만 사용되나, 후에 다른 곳에서도 사용 가능해보입니다. ex) 건전하지 않은 닉네임 강제 변경 등
유틸 클래스를 하나 따로 만들면 어떨까요? 
+) 여기에 둘 거라면 private으로 수정 부탁드립니다.

2024-03-20 00:50 UTC, minnim1010 commented on src/main/java/com/formssafe/domain/oauth/service/OAuthService.java
> +        String nickname;
💊 그럴 일이 거의 없어보이지만, 8개 문자로 가능한 모든 user 닉네임이 존재하는 경우 무한 루프가 돌게 되고, 계속해서 쿼리가 실행됩니다. 퍼포먼스 문제가 있을 것이라 생각되는데, 현재 시각 + 랜덤 문자열 형식으로 만들면 어떨까요?

2024-03-20 00:50 UTC, minnim1010 commented on src/main/java/com/formssafe/domain/user/controller/UserController.java
>      @Operation(summary="프로필 가져오기", description="세션의 정보로부터 프로필 정보 가져와서 return")
❗️개행 부탁드립니다.

2024-03-20 00:50 UTC, minnim1010 commented on src/main/java/com/formssafe/domain/user/controller/UserController.java
> +    public ResponseEntity<UserProfileDto> getUserProfile(HttpServletRequest request) {
세션에 저장된 유저 Id를 가져오려고 request를 받아오는 것 같습니다.
❗️@AuthenticationPrincipal을 사용하면 유저 Id를 가져올 수 있습니다. SessionAuthenticationFilter 확인하시고 변경하시면 좋을 것 같아요.

2024-03-20 00:50 UTC, minnim1010 commented on src/main/java/com/formssafe/domain/user/service/UserService.java
> +    @Autowired
❗️생성자 빈 주입 방식으로 변경 부탁드립니다.

2024-03-20 00:50 UTC, minnim1010 commented on src/main/java/com/formssafe/domain/user/service/UserService.java
>  public class UserService {
lazy 로딩 시 에러가 날 수 있으니 @Transcational(readOnly=true) 옵션 부탁드립니다.

2024-03-20 00:50 UTC, minnim1010 commented on src/main/java/com/formssafe/domain/user/service/UserService.java
> +            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "존재하지 않는 userId입니다.");
❗️ExceptionHandlerAdvice를 만들었으니 명시적으로 줄 필요 없이, RestControllerAdvice의 basePackages에 UserController 추가 후 에러만 던지면 됩니다.

2024-03-20 00:50 UTC, minnim1010 commented on src/main/java/com/formssafe/domain/user/service/UserService.java
> +        return new UserProfileDto(user.id(), user.nickname(), user.email(), user.imageUrl());
❗️converter 사용 부탁드립니다.

2024-03-20 00:50 UTC, minnim1010 commented on src/main/java/com/formssafe/infra/oauth/google/authcode/GoogleAuthCodeRequestUrlProvider.java
> +                .queryParam("access_type", "offline")
왜 필요한지 설명 부탁드립니다!

2024-03-20 00:50 UTC, minnim1010 commented on src/main/java/com/formssafe/infra/oauth/google/client/GoogleApiClient.java
> +//    GoogleToken fetchToken(@RequestParam MultiValueMap<String, String> params);
👍🏻 MultiValueMap 대신 Param을 명시해주는 게 더 좋아보입니다! 더 많아진다면 class 정의가 필요하겠으나 지금은 바로 확인 가능해서 더 좋다고 생각이 드네요!

2024-03-20 00:50 UTC, minnim1010 commented on src/main/java/com/formssafe/infra/oauth/google/dto/GoogleMemberResponse.java
> +public class GoogleMemberResponse {
❗️DTO는 레코드로 정의하기로 이야기됐습니다! 레코드로 수정 부탁드립니다!

2024-03-20 00:50 UTC, minnim1010 commented on src/main/java/com/formssafe/infra/oauth/google/client/GoogleApiClient.java
> +    GoogleAccessToken fetchToken(@RequestParam("grant_type") String grantType,
💊 GoogleAccessToken -> GoogleAccessTokenByCode
GoogleRefreshToekn -> GoogleAccessTokenByRefreshToken
은 어떨까요?

2024-03-20 00:50 UTC, minnim1010 commented on src/main/java/com/formssafe/domain/user/service/UserService.java
> +        //1. db에서 user 가져오기
❗️주석 삭제 부탁드립니다~

2024-03-20 00:50 UTC, minnim1010 commented on src/main/java/com/formssafe/domain/user/service/UserService.java
> +        if(!user.nickname().equals(nickname) && !userRepository.existsByNickname(nickname)){
💊 예외 처리 먼저하고 닉네임 변경 로직을 수행하는 게 가독성이 더 좋아보입니다.

2024-03-20 00:50 UTC, minnim1010 commented on src/main/java/com/formssafe/domain/user/service/UserService.java
> +            BeanUtils.copyProperties(nickname, user, "nickname");
혹시 이건 어떤 로직인가요? user.updateNickname(nickname)일 거라 예상했는데 문제가 있었나요?

2024-03-20 00:50 UTC, minnim1010 commented on src/main/java/com/formssafe/domain/user/controller/UserController.java
> +        return ResponseEntity.ok(userService.getProfile(request));
💊 개인적으로는 @ResponseStatus() 사용하는 게 가독성이 더 좋아보여서 사용하는데, ResponseEntity vs @ResponseStatus 중 논의가 필요해보입니다.

2024-03-20 08:10 UTC, gurwls0122 commented on src/main/java/com/formssafe/domain/user/entity/User.java
> +@Setter
엔티티에서 nickname은 받아온 닉네임이 아닌 만들어주는 닉네임으로 업데이트 해줘야되는 로직이 있어서 @setter는 없애고 setNickname 만들어주겠습니당.

2024-03-21 00:24 UTC, gurwls0122 commented on src/main/java/com/formssafe/domain/user/entity/User.java
>  @AllArgsConstructor
AllArgsConstructor 삭제하고, 생성자 정의해서 Builder로 선언했슴다.

2024-03-21 00:33 UTC, gurwls0122 commented on src/main/java/com/formssafe/domain/user/service/UserService.java
> +        //1. db에서 user 가져오기
확인했습니다!

2024-03-21 00:39 UTC, gurwls0122 commented on src/main/java/com/formssafe/infra/oauth/google/client/GoogleApiClient.java
> +    GoogleAccessToken fetchToken(@RequestParam("grant_type") String grantType,
좋습니다!

2024-03-21 00:39 UTC, gurwls0122 commented on src/main/java/com/formssafe/domain/oauth/client/OauthMemberClient.java
> +    void deleteAccount(String code);
확인했습니다.

2024-03-21 22:23 UTC, minnim1010 commented on src/main/java/com/formssafe/domain/user/controller/UserController.java
> +    public void patchNickname(HttpServletRequest request, @RequestBody NicknamePatchDto nickname) {
NicknamePatchDto -> NicknameUpdateDto가 더 직관적으로 느껴지는 것 같습니다. 수정해보면 어떨까요?

2024-03-21 22:37 UTC, minnim1010 requested changes
고생하셨습니다~

2024-03-21 22:37 UTC, minnim1010 commented on src/main/java/com/formssafe/domain/user/controller/UserController.java
> +    public void patchNickname(HttpServletRequest request, @RequestBody NicknamePatchDto nickname) {
+ Http method를 controller 메서드명에 사용하는 것보다 updateNickname과 같이 어떤 "기능"을 수행하는지 작성하면 더 좋을 것 같습니다.

2024-03-21 22:37 UTC, minnim1010 commented on src/main/java/com/formssafe/domain/user/dto/UserResponse.java
> +        public static UserProfileDto convertEntityToDto(User user){
❗️개행 부탁드려요~

2024-03-21 22:37 UTC, minnim1010 commented on src/main/java/com/formssafe/domain/user/entity/User.java
> +    public User(Long id, OauthId oauthId, String nickname, String email, Authority authority, String imageUrl, LocalDateTime createTime, String refreshToken){
❗️private으로 변경 부탁드립니다! public이면 생성자도 사용할 수 있게 되니까요~
+) 위치는 속성 바로 밑에 부탁드려요~

2024-03-21 22:37 UTC, minnim1010 commented on src/main/java/com/formssafe/domain/user/service/UserService.java
> +    @Autowired
❗️@Autowired 안 붙여도 됩니다. 삭제 부탁드려요~

2024-03-21 22:37 UTC, minnim1010 commented on src/main/java/com/formssafe/domain/user/service/UserService.java
> +            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "존재하지 않는 userId입니다.");
❗️throw 없어야 합니다. orElseThrow 파라미터 확인해주세요~

2024-03-21 22:37 UTC, minnim1010 commented on src/main/java/com/formssafe/domain/user/service/UserService.java
> +    public Long getUserIdFromSession(HttpServletRequest request){
❗️private으로 바꿔주세요.

2024-03-21 22:37 UTC, minnim1010 commented on src/main/java/com/formssafe/domain/user/service/UserService.java
> +        else{
❗️throw 했는데 else 사용할 필요 없어보입니다~

2024-03-25 04:41 UTC, merged